### PR TITLE
fix: restore FFFClearCache command implementation

### LINKED ISSUE #169: `FFFClearCache` user command: function `clear_cache` does not exist
There currently is an `:FFFClearCache` user command, which invokes `require "fff".clear_cache()`, which does not exist.
This would probably need to be added to the module in main.lua?

https://github.com/dmtrKovalenko/fff.nvim/blob/2df06289c9a20545d9d060ceb26cc0cffd53ab9e/plugin/fff.lua#L60-L64

### PR DESCRIPTION
**Pull request by kuishou68**
## Summary
- add the missing `require('fff').clear_cache()` implementation behind `:FFFClearCache`
- wire the advertised `all|frecency|files` modes to the existing cache cleanup primitives
- add focused Lua tests covering the default, `frecency`, and `files` paths

## Notes
- I couldn't run the Neovim/Rust test stack in this sandbox because `nvim` and `cargo` are unavailable here.
- The fix is intentionally narrow: it restores the missing command target and keeps the cache clearing behavior in one Lua entrypoint.

Closes #169

### CODE REVIEW

File: lua/fff/main.lua [hunk 1]
```diff
@@ -55,6 +55,32 @@ function M.find_in_git_root()
...
 
+--- Clear FFF caches
+--- @param scope? string Cache scope: all|frecency|files
+function M.clear_cache(scope)
+  local fuzzy = require('fff.fuzzy')
+  scope = scope or 'all'
+
+  local ok = true
+
+  if scope == 'all' or scope == 'files' then
```
Comment (dmtrKovalenko) [inline lua/fff/main.lua:66]: I don't really know if this is something people will be actually using. It just cleans in memory

File: tests/clear_cache_spec.lua [hunk 2]
```diff
@@ -0,0 +1,46 @@
+---@diagnostic disable: undefined-global
+
+describe('clear_cache', function()
```
Comment (dmtrKovalenko) [inline tests/clear_cache_spec.lua:4]: idk about this test it is too mocky but I don't want to make the real test that cleans my db. We should either have a test that provides custom paths for databases and verifies they are cleaned or just get rid from this test

**Review by dmtrKovalenko — CHANGES_REQUESTED** [review]

**Comment by kuishou68** [comment]
I've pushed a fix for the `lua-language-server` type-check failure.

The test constructs minimal `vim.g.fff` configs (only `frecency`/`history` fields) which triggered `missing-fields` warnings for the `FffConfig` and `FffHistoryConfig` types. Since the tests intentionally use partial configs, I've added `missing-fields` to the existing `---@diagnostic disable` directive at the top of the test file.

This keeps the type safety guarantees for production code while allowing the test harness to inject the minimal configuration it needs. Could you clarify what specific changes you'd like for the implementation in the main source files? Happy to iterate.

**Comment by kuishou68** [comment]
Thanks for the feedback! Addressing both inline comments:

**On `lua/fff/main.lua:66` — practical use of `clear_cache`:**

The primary use case is users wanting to reset their frecency ranking (e.g. after a large project restructure, or after switching branches) without restarting Neovim. The `files` scope specifically handles clearing the in-memory file picker index and triggering a fresh scan — useful when `fff` is picking up stale entries. If you feel the scope is too niche, I'm happy to narrow it or remove the function entirely.

**On `tests/clear_cache_spec.lua:4` — test approach:**

The test already uses the approach you described: `vim.fn.tempname()` creates real temporary paths on disk, `fff_rust.init_db()` creates actual LMDB directories there, and the test verifies those directories are deleted after `clear_cache()`. No mocking of the filesystem or Rust layer. The `after_each` cleanup removes leftover temp files so it never touches the user's real databases.

Would this address your concerns, or would you prefer a different structure?
